development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: criteria
  username: postgres
  password: postgres
  template: template0
  
test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: criteria
  pool:     5
  username: postgres
  password: postgres
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: criteria
  pool:     5
  username: postgres
  password: postgres
  template: template0
